import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Generates all necessary Flutter localization setup files
 * This connects the generated ARB files with Flutter's language change system
 */

export async function generateLocalizationSetup(): Promise<void> {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
        vscode.window.showErrorMessage('No workspace open.');
        return;
    }

    const rootPath = workspaceFolders[0].uri.fsPath;

    // Get existing languages from ARB files
    const l10nDir = path.join(rootPath, 'lib', 'l10n');
    const existingLocales = getExistingLocales(l10nDir);

    if (existingLocales.length === 0) {
        vscode.window.showWarningMessage('No ARB files found. Please run "Flutter Auto Localizer: Start" first to extract strings.');
        return;
    }

    const results: string[] = [];

    // 1. Generate l10n.yaml
    const l10nYamlCreated = await generateL10nYaml(rootPath);
    if (l10nYamlCreated) results.push('l10n.yaml');

    // 2. Update pubspec.yaml
    const pubspecUpdated = await updatePubspecYaml(rootPath);
    if (pubspecUpdated) results.push('pubspec.yaml');

    // 3. Generate LocaleProvider
    const providerCreated = await generateLocaleProvider(rootPath, existingLocales);
    if (providerCreated) results.push('locale_provider.dart');

    // 4. Generate Language Switcher Widget
    const switcherCreated = await generateLanguageSwitcher(rootPath, existingLocales);
    if (switcherCreated) results.push('language_switcher.dart');

    // 5. Generate setup instructions
    const instructionsCreated = await generateSetupInstructions(rootPath, existingLocales);
    if (instructionsCreated) results.push('LOCALIZATION_SETUP.md');

    if (results.length > 0) {
        vscode.window.showInformationMessage(
            `✅ Flutter Localization Setup Complete! Created/Updated: ${results.join(', ')}`
        );

        // Open the instructions file
        const instructionsPath = path.join(rootPath, 'LOCALIZATION_SETUP.md');
        if (fs.existsSync(instructionsPath)) {
            const doc = await vscode.workspace.openTextDocument(instructionsPath);
            await vscode.window.showTextDocument(doc);
        }
    } else {
        vscode.window.showInformationMessage('All setup files already exist. No changes made.');
    }
}

function getExistingLocales(l10nDir: string): string[] {
    const locales: string[] = [];

    if (fs.existsSync(l10nDir)) {
        const files = fs.readdirSync(l10nDir);
        files.forEach(file => {
            const match = file.match(/^app_([a-zA-Z-]+)\.arb$/);
            if (match) {
                locales.push(match[1]);
            }
        });
    }

    return locales;
}

async function generateL10nYaml(rootPath: string): Promise<boolean> {
    const l10nYamlPath = path.join(rootPath, 'l10n.yaml');

    if (fs.existsSync(l10nYamlPath)) {
        return false; // Already exists
    }

    const content = `# Flutter Localization Configuration
# Generated by Flutter Auto Localizer

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

# Uncomment for nullable getter (removes the ! operator requirement)
# nullable-getter: false
`;

    fs.writeFileSync(l10nYamlPath, content, 'utf8');
    return true;
}

async function updatePubspecYaml(rootPath: string): Promise<boolean> {
    const pubspecPath = path.join(rootPath, 'pubspec.yaml');

    if (!fs.existsSync(pubspecPath)) {
        vscode.window.showErrorMessage('pubspec.yaml not found!');
        return false;
    }

    let content = fs.readFileSync(pubspecPath, 'utf8');
    let modified = false;

    // Check if flutter_localizations is already added
    if (!content.includes('flutter_localizations:')) {
        // Find dependencies: section and add after flutter: sdk: flutter
        const flutterSdkMatch = content.match(/(dependencies:\s*\n\s*flutter:\s*\n\s*sdk:\s*flutter)/);
        if (flutterSdkMatch) {
            content = content.replace(
                flutterSdkMatch[0],
                `${flutterSdkMatch[0]}
  flutter_localizations:
    sdk: flutter
  intl: any`
            );
            modified = true;
        }
    }

    // Check if generate: true is in flutter section
    if (!content.includes('generate: true')) {
        const flutterSectionMatch = content.match(/(flutter:\s*\n)/);
        if (flutterSectionMatch) {
            // Find the position after "flutter:" and add generate: true
            const flutterIndex = content.indexOf('flutter:');
            const nextLineIndex = content.indexOf('\n', flutterIndex) + 1;

            // Check what's after flutter:
            const afterFlutter = content.substring(nextLineIndex);
            const indentMatch = afterFlutter.match(/^(\s*)/);
            const indent = indentMatch ? indentMatch[1] : '  ';

            content = content.substring(0, nextLineIndex) +
                `${indent}generate: true\n` +
                content.substring(nextLineIndex);
            modified = true;
        }
    }

    if (modified) {
        fs.writeFileSync(pubspecPath, content, 'utf8');
        return true;
    }

    return false;
}

async function generateLocaleProvider(rootPath: string, locales: string[]): Promise<boolean> {
    const providerDir = path.join(rootPath, 'lib', 'core', 'providers');
    const providerPath = path.join(providerDir, 'locale_provider.dart');

    if (fs.existsSync(providerPath)) {
        return false;
    }

    // Create directory if needed
    if (!fs.existsSync(providerDir)) {
        fs.mkdirSync(providerDir, { recursive: true });
    }

    const defaultLocale = locales.includes('en') ? 'en' : locales[0];

    const content = `import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// LocaleProvider - Manages app language state
/// Generated by Flutter Auto Localizer
///
/// Usage:
/// 1. Wrap your MaterialApp with ChangeNotifierProvider
/// 2. Use Consumer<LocaleProvider> or context.watch<LocaleProvider>()
/// 3. Call localeProvider.setLocale(Locale('es')) to change language

class LocaleProvider extends ChangeNotifier {
  static const String _localeKey = 'app_locale';

  Locale _locale = const Locale('${defaultLocale}');

  Locale get locale => _locale;

  /// Initialize locale from saved preferences
  Future<void> loadSavedLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLocale = prefs.getString(_localeKey);
    if (savedLocale != null) {
      _locale = Locale(savedLocale);
      notifyListeners();
    }
  }

  /// Change the app locale and persist to storage
  Future<void> setLocale(Locale locale) async {
    if (_locale == locale) return;

    _locale = locale;
    notifyListeners();

    // Save to preferences
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, locale.languageCode);
  }

  /// Get list of supported locales
  /// Update this list when you add new languages
  static List<Locale> get supportedLocales => [
${locales.map(l => `    const Locale('${l}'),`).join('\n')}
  ];
}
`;

    fs.writeFileSync(providerPath, content, 'utf8');
    return true;
}

async function generateLanguageSwitcher(rootPath: string, locales: string[]): Promise<boolean> {
    const widgetsDir = path.join(rootPath, 'lib', 'core', 'widgets');
    const switcherPath = path.join(widgetsDir, 'language_switcher.dart');

    if (fs.existsSync(switcherPath)) {
        return false;
    }

    if (!fs.existsSync(widgetsDir)) {
        fs.mkdirSync(widgetsDir, { recursive: true });
    }

    const languageNames: Record<string, string> = {
        'en': 'English',
        'es': 'Español',
        'fr': 'Français',
        'de': 'Deutsch',
        'it': 'Italiano',
        'pt': 'Português',
        'ru': 'Русский',
        'ja': '日本語',
        'ko': '한국어',
        'zh-cn': '简体中文',
        'zh-tw': '繁體中文',
        'ar': 'العربية',
        'hi': 'हिन्दी',
        'si': 'සිංහල',
        'ta': 'தமிழ்',
        'th': 'ไทย',
        'vi': 'Tiếng Việt',
        'tr': 'Türkçe',
        'pl': 'Polski',
        'nl': 'Nederlands',
        'sv': 'Svenska',
        'da': 'Dansk',
        'fi': 'Suomi',
        'no': 'Norsk',
        'cs': 'Čeština',
        'el': 'Ελληνικά',
        'he': 'עברית',
        'id': 'Bahasa Indonesia',
        'ms': 'Bahasa Melayu',
        'uk': 'Українська',
        'bn': 'বাংলা',
        'te': 'తెలుగు',
        'mr': 'मराठी',
        'gu': 'ગુજરાતી',
        'kn': 'ಕನ್ನಡ',
        'ml': 'മലയാളം',
        'pa': 'ਪੰਜਾਬੀ',
        'ro': 'Română',
        'hu': 'Magyar',
        'sk': 'Slovenčina',
        'bg': 'Български',
        'sr': 'Српски',
        'hr': 'Hrvatski',
        'sl': 'Slovenščina',
        'lt': 'Lietuvių',
        'lv': 'Latviešu',
        'et': 'Eesti',
        'fil': 'Filipino',
        'sw': 'Kiswahili',
        'af': 'Afrikaans',
        'ca': 'Català',
        'eu': 'Euskara',
        'gl': 'Galego',
    };

    const localeEntries = locales.map(l => {
        const name = languageNames[l] || l.toUpperCase();
        return `    '${l}': '${name}',`;
    }).join('\n');

    const content = `import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/locale_provider.dart';

/// Language Switcher Widget
/// Generated by Flutter Auto Localizer
///
/// Usage: Simply add LanguageSwitcher() to your settings page or app bar

class LanguageSwitcher extends StatelessWidget {
  const LanguageSwitcher({super.key});

  static const Map<String, String> _languageNames = {
${localeEntries}
  };

  @override
  Widget build(BuildContext context) {
    return Consumer<LocaleProvider>(
      builder: (context, localeProvider, child) {
        return DropdownButton<String>(
          value: localeProvider.locale.languageCode,
          icon: const Icon(Icons.language),
          underline: const SizedBox(),
          onChanged: (String? newValue) {
            if (newValue != null) {
              localeProvider.setLocale(Locale(newValue));
            }
          },
          items: _languageNames.entries.map((entry) {
            return DropdownMenuItem<String>(
              value: entry.key,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(entry.value),
                  const SizedBox(width: 8),
                  Text(
                    '(\${entry.key})',
                    style: TextStyle(
                      color: Colors.grey[600],
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
        );
      },
    );
  }
}

/// Alternative: Language Switcher as a ListTile for settings screens
class LanguageSwitcherTile extends StatelessWidget {
  const LanguageSwitcherTile({super.key});

  static const Map<String, String> _languageNames = {
${localeEntries}
  };

  @override
  Widget build(BuildContext context) {
    return Consumer<LocaleProvider>(
      builder: (context, localeProvider, child) {
        final currentLang = _languageNames[localeProvider.locale.languageCode] ??
            localeProvider.locale.languageCode;

        return ListTile(
          leading: const Icon(Icons.language),
          title: const Text('Language'),
          subtitle: Text(currentLang),
          trailing: const Icon(Icons.arrow_forward_ios, size: 16),
          onTap: () => _showLanguageDialog(context, localeProvider),
        );
      },
    );
  }

  void _showLanguageDialog(BuildContext context, LocaleProvider localeProvider) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Select Language'),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView.builder(
            shrinkWrap: true,
            itemCount: _languageNames.length,
            itemBuilder: (context, index) {
              final entry = _languageNames.entries.elementAt(index);
              final isSelected = localeProvider.locale.languageCode == entry.key;

              return ListTile(
                title: Text(entry.value),
                trailing: isSelected
                    ? const Icon(Icons.check, color: Colors.green)
                    : null,
                onTap: () {
                  localeProvider.setLocale(Locale(entry.key));
                  Navigator.of(context).pop();
                },
              );
            },
          ),
        ),
      ),
    );
  }
}

/// Alternative: Bottom Sheet Language Selector
class LanguageBottomSheet extends StatelessWidget {
  const LanguageBottomSheet({super.key});

  static const Map<String, String> _languageNames = {
${localeEntries}
  };

  static void show(BuildContext context) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) => const LanguageBottomSheet(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<LocaleProvider>(
      builder: (context, localeProvider, child) {
        return Container(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Select Language',
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 16),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: _languageNames.entries.map((entry) {
                  final isSelected = localeProvider.locale.languageCode == entry.key;
                  return ChoiceChip(
                    label: Text(entry.value),
                    selected: isSelected,
                    onSelected: (selected) {
                      if (selected) {
                        localeProvider.setLocale(Locale(entry.key));
                        Navigator.of(context).pop();
                      }
                    },
                  );
                }).toList(),
              ),
              const SizedBox(height: 16),
            ],
          ),
        );
      },
    );
  }
}
`;

    fs.writeFileSync(switcherPath, content, 'utf8');
    return true;
}

async function generateSetupInstructions(rootPath: string, locales: string[]): Promise<boolean> {
    const instructionsPath = path.join(rootPath, 'LOCALIZATION_SETUP.md');

    const content = `# 🌍 Flutter Localization Setup Guide

Generated by **Flutter Auto Localizer**

## ✅ What's Been Created

1. **l10n.yaml** - Flutter localization configuration
2. **pubspec.yaml** - Updated with required dependencies
3. **lib/core/providers/locale_provider.dart** - State management for language
4. **lib/core/widgets/language_switcher.dart** - Ready-to-use language selector widgets

## 📦 Required Dependencies

Run this command to install the required packages:

\`\`\`bash
flutter pub add provider shared_preferences
flutter pub get
\`\`\`

## 🔧 Setup Steps

### Step 1: Update your main.dart

\`\`\`dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'core/providers/locale_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize locale provider
  final localeProvider = LocaleProvider();
  await localeProvider.loadSavedLocale();

  runApp(
    ChangeNotifierProvider.value(
      value: localeProvider,
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<LocaleProvider>(
      builder: (context, localeProvider, child) {
        return MaterialApp(
          title: 'Your App',

          // 🌍 LOCALIZATION CONFIGURATION
          locale: localeProvider.locale,
          supportedLocales: AppLocalizations.supportedLocales,
          localizationsDelegates: AppLocalizations.localizationsDelegates,

          home: const HomeScreen(),
        );
      },
    );
  }
}
\`\`\`

### Step 2: Use the Language Switcher

Add the language switcher to your settings page or app bar:

\`\`\`dart
import 'package:your_app/core/widgets/language_switcher.dart';

// Option 1: Dropdown (for AppBar)
AppBar(
  title: const Text('Settings'),
  actions: [
    const LanguageSwitcher(),
  ],
)

// Option 2: ListTile (for Settings screen)
const LanguageSwitcherTile()

// Option 3: Bottom Sheet
ElevatedButton(
  onPressed: () => LanguageBottomSheet.show(context),
  child: const Text('Change Language'),
)
\`\`\`

### Step 3: Use Localized Strings

\`\`\`dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

// In your widgets:
Text(AppLocalizations.of(context)!.welcomeMessage)
\`\`\`

## 🔄 Generate Localization Files

After adding new strings or translations, run:

\`\`\`bash
flutter gen-l10n
\`\`\`

Or just run your app - Flutter automatically generates the files.

## 📁 Your Current Languages

${locales.map(l => `- \`${l}\``).join('\n')}

## 🚀 Adding New Languages

1. Run "Flutter Auto Localizer: Start" on any Dart file
2. Select additional languages from the list
3. ARB files will be created and translated automatically

## 📝 Manual Translation Editing

Edit files in \`lib/l10n/\`:
${locales.map(l => `- \`app_${l}.arb\``).join('\n')}

## ❓ Troubleshooting

### "AppLocalizations not found"
1. Make sure \`l10n.yaml\` exists in project root
2. Run \`flutter pub get\`
3. Run \`flutter gen-l10n\` or restart your IDE

### "The method 'of' isn't defined"
Add this import to your file:
\`\`\`dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
\`\`\`

### Hot reload doesn't update language
Language changes require a hot restart, not just hot reload.

---

Generated with ❤️ by Flutter Auto Localizer
`;

    fs.writeFileSync(instructionsPath, content, 'utf8');
    return true;
}

export { getExistingLocales };
